module_name: Block Manufacturer
compatible_versions: 1.0.0+
author: thirty bees
category: front office
tags:
  - manufacturer
  - brand
  - manufacturers
description_short: The block manufacturer allows you to dislay a block link manufacturers
description: description.md
images:
  - image-1.png
license: AFL